### ISSUE TITLE
[Fatal error] Appetite requests non-existent version of GoProne as a dependency 

### ISSUE THREAD

**Issue by kawaiicakes** [CCr4ft3r/appetite#10]
**Minecraft 1.19.2**
**Forge Mod Loader 43.2.14**
**Appetite 1.5.1**

Appetite requests version 2.4.0 of GoProne when the latter is installed. Only 2.0.4 exists for 1.19.2.

**Comment by CCr4ft3r** [comment]
Sorry it took so long - it's now fixed in 1.5.2
