### ISSUE TITLE
{Feature Request} More options (Configurable Day/Evening/Night, & Frozen Foods)

### ISSUE THREAD

**Issue by togera13** [CCr4ft3r/appetite#12]
### Hunger from Day/Evening/Night ###
What if we had the ability to set a configurable amount of hunger gain every morning evening & night? So, the player would need more of a breakfast, lunch, & dinner. (or maybe just Evening & day since minecraft days are short so idk if it would be bad to include day & night, or I mean you could just let us turn on or off hunger for each individual part of the day.)

### Configurable Frozen foods ###
Add the ability to specify a list of items that count as frozen, as there are quite a few mods that add things like popsicles or frozen foods. For example: Rotton Creatures (Frozen Rotten Flesh), Farmer's Delight (Melon Popsicle), End's Delight (Chorus Fruit Popsicle), Collector's Reap (Lime Popsicle), Beach Party (Coconut Popsicle, Melon Popsicle, Cactus Popsicle, Sweetberry Sundae, Coconut Sundae, Chocolate Sundae, Sweetberry Icecream, Chocolate Icecream).

**Comment by CCr4ft3r** [comment]
I like your ideas 👍 The second one was already requested: https://github.com/CCr4ft3r/appetite/issues/8
Your list of examples seems very reasonable to me.
I think the best way to implement that would be a tag is_frozen_food that includes your listed ones and can be extended (or changed) by adding a separate datapack with Appetites namespace including the tags/is_frozen_food.json.

I will include both in the next update. Thx for the suggestions.
