### ISSUE TITLE
Feature Request - Adding Foods in config for frozen Appetite 

### ISSUE THREAD

**Issue by LeonKappaX** [CCr4ft3r/appetite#8]
Hey! I've been trying out your mod for a pack that I am working on and I really like the idea of the mod in general and also the frozen appetite mechanic. However I think, if it is possible for you to implement, an option to add more foods to the list of foods that can freeze the appetite would be amazing, especially for pack devs!

**Comment by CCr4ft3r** [comment]
Yes 👍 I will include that feature in the next update configurable via datapack tags (including some defaults)
